### PR TITLE
Various cleanups

### PR DESCRIPTION
**Pull request by akx**
This PR:

* cleans up requirements (could still clean up more; e.g. inference shouldn't require all of the things training does)
* fixes some minor bugs (e.g. leaky globals, this and that)
* makes the project work even without `bitsandbytes`
* deduplicates some code

### CODE REVIEW

**Comment by akx** [comment]
NB: I haven't run this branch on Valohai yet (I don't have access to the project/datasets/S3 bucket currently used), so if someone wants to give that a shot...

**Review by tokkoro — APPROVED** [review]
Changes are clean and clear. 

Was not able to properly run executions as I don't have access to the data store.

**Review by SofiaChar — APPROVED** [review]
Looking good

**Comment by tokkoro** [comment]
@akx can you rebase so it can be merged? :)

**Comment by akx** [comment]
@tokkoro Done. Rebasing took a while since I had to untangle some of the duplicate work done in a4b54510b89b741cf8c83e1b5930a0f05d475998.

**Pull request merged**
